[project]
name = "nova-act-qa-e2e-test"
version = "0.1.0"
requires-python = ">= 3.13"

[project.optional-dependencies]
dev = [
    "nova-act",
    "pytest",
]

[build-system]
requires = ["setuptools==80.9", "wheel==0.45.1"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = ["test_*", "run_test"]
filterwarnings = [
    "ignore::pytest.PytestUnhandledThreadExceptionWarning:nova_act.impl.keyboard_event_watcher"
]
