name: Nova-Act-QA E2E Tests 
# 発火タイミング
on:
  push:
    branches: ['dev','main']
  workflow_dispatch:

# 権限
permissions:
  contents: read
  checks: write


jobs:
  nova-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (clone) target repository
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install nova-act
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: check nova-act version
        run: pip list

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm ci

      - name: Run local server
        run: npm run dev &

      - name: === Run Nova-Act tests ===
        id: run-tests
        env:
          NOVA_ACT_API_KEY: ${{ secrets.NOVA_ACT_API_KEY }}
        run: |
          python -m pytest --junit-xml tests/result.xml -v
        continue-on-error: true
      
        # テスト結果をGitHub上で表示する
      - name: display results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: tests/*.xml

      - name: Archive test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/*.log
          retention-days: 1